### PR TITLE
Czech translation update

### PR DESCRIPTION
**Pull request by R3gi**
Hello,
I have updated Czech translation. There were some bugs, typos and inaccuracies.

Btw. I am still quite new to GitHub and it's litle bit confusing for me. I have no idea how to merge patches, so I had to create pull request for every single file in my fork, then open it and merge it manually with my master branch. Please, is there some easier solution? Thanks :)

### CODE REVIEW

**Comment by tierra** [comment]
Assuming you're not too familiar with git either, you can also just install the GitHub desktop client (GitHub for Mac, or GitHub for Windows), and have it load up your fork. Then you can make changes to all the files at once, and use the desktop app to commit those changes, and push them back to your fork, or create a pull request directly to me from the app.

This is fine though, everything looks right. I'll merge this shortly.

**Comment by R3gi** [comment]
Thank you, I hope everything is fine :) And is there a way to do that directly online, in the web version? Unfortunatelly, it seems that almost all help files/documentation is made for desktop app and it's cmd only :'-(

**Comment by tierra** [comment]
There is one easier option using this website that avoids needing to open several pull requests. You can create a new branch (press 'w' with your fork open, and type in a new name for your branch, and hit enter). Then while browsing on that branch, you can edit all files, making individual commits for each still, and when you're finished, open your [branches](https://github.com/R3gi/topicsolved/branches) page, and click "New pull request" from there.

But the only way to do it all in one commit is to actually clone the git repository on your desktop, and edit the files there. The GitHub application is a frontend to the git application, which doesn't require typing in commands to make commits or anything though. You should be able to do it all without opening up a terminal.

**Comment by tierra** [comment]
At some point in the future, I'll probably take the time to get this extension setup in Transifex so it's easier on everyone to contribute and update translations.

**Comment by R3gi** [comment]
Thank you very much for this very detailed answer! :)

**Pull request closed without merging**
